Repository zanzanbari/WAL, pull requests merged in 2022-08, with the labels that each got.

#25 [Feat] Onboarding Service 서버 통신 (#15)
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/Constant.swift
  WAL/WAL/Global/Protocol/Protocol.swift
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Network/API/Onboard/OnboardAPI.swift
  WAL/WAL/Network/DataModel/Auth/Login.swift
  WAL/WAL/Network/DataModel/Auth/Logout.swift
  WAL/WAL/Network/DataModel/Auth/Reissue.swift
  WAL/WAL/Network/DataModel/Onboard/Onboard.swift
  WAL/WAL/Network/DataModel/Onboard/OnboardRequest.swift
  WAL/WAL/Network/Service/Auth/AuthService.swift
  WAL/WAL/Network/Service/Onboard/OnboardService.swift
  WAL/WAL/Network/Utility/BaseTargetType.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Onboarding/View/AlarmCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/CategoryCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/OnboardingCollectionViewCell.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/Controller/ZanzanbariViewController.swift
  WAL/WAL/Screen/Setting/View/Component/ResignHeaderView.swift
  WAL/WAL/Screen/Setting/View/MyInfoTableViewCell.swift
Labels: 코드리뷰좀제발, P0, 서버통신, 훌이킴

#26 [Feat] Main Service 서버 통신 (#22)
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcodeproj/xcshareddata/xcschemes/WAL.xcscheme
  WAL/WAL/Network/API/Main/MainAPI.swift
  WAL/WAL/Network/DataModel/Main/MainResponse.swift
  WAL/WAL/Network/Service/Main/MainService.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/Model/WALContentType.swift
  WAL/WAL/Screen/Main/Model/WALStatus.swift
  WAL/WAL/Screen/Main/View/MainContentView.swift
  WAL/WAL/Screen/Main/View/MainItemCell.swift
Labels: 코드리뷰좀제발, 서버통신, 소깡이

#28 [Feat] Setting Service 서버 통신 (#21)
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/Constant.swift
  WAL/WAL/Global/Protocol/Protocol.swift
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Network/API/Onboard/OnboardAPI.swift
  WAL/WAL/Network/API/Setting/SettingAPI.swift
  WAL/WAL/Network/DataModel/Auth/LoginModel.swift
  WAL/WAL/Network/DataModel/Onboard/OnboardRequest.swift
  WAL/WAL/Network/DataModel/Setting/UserAlarm.swift
  WAL/WAL/Network/DataModel/Setting/UserCategory.swift
  WAL/WAL/Network/DataModel/Setting/UserInfo.swift
  WAL/WAL/Network/DataModel/Setting/UserRequest.swift
  WAL/WAL/Network/Service/Setting/SettingService.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Onboarding/View/AlarmCollectionViewCell.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
  WAL/WAL/Screen/Setting/Controller/ZanzanbariViewController.swift
  WAL/WAL/Screen/Setting/Model/Setting.swift
  WAL/WAL/Screen/Setting/View/Component/ZanzanView.swift
  WAL/WAL/Screen/Setting/View/MyInfoTableViewCell.swift
Labels: 코드리뷰좀제발, 서버통신, 훌이킴

#31 [Feat] Creating Service 서버 통신 (#20)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Network/API/Create/CreateAPI.swift
  WAL/WAL/Network/DataModel/Create/Reserve.swift
  WAL/WAL/Network/Service/Create/CreateService.swift
  WAL/WAL/Screen/Create/Controller/CreateBackPopupViewController.swift
  WAL/WAL/Screen/Create/Controller/CreateFinishedViewController.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
  WAL/WAL/Screen/Create/Model/ReservedDate.swift
  WAL/WAL/Screen/Create/View/DatePickerTableViewCell.swift
Labels: 코드리뷰좀제발, P0, 서버통신, 밴톨이

#32 [Feat] 히스토리 서버 연결 (#17)
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/Extension/UILabel+.swift
  WAL/WAL/Network/API/History/HistoryAPI.swift
  WAL/WAL/Network/DataModel/History/DeleteHistoryResponse.swift
  WAL/WAL/Network/DataModel/History/HistoryResponse.swift
  WAL/WAL/Network/Service/History/HistoryService.swift
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/1024.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/120-1.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/120.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/180.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/40.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/58.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/60.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/80.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/87.png
  WAL/WAL/Resource/Asset/Asset.xcassets/AppIcon.appiconset/Contents.json
  WAL/WAL/Resource/Support/Info.plist
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
  WAL/WAL/Screen/History/View/HistoryTableViewCell.swift
Labels: 오류해결, 레이아웃, 로직구현, 소깡이, 이준

#34 [Fix] 바뀐 회원 탈퇴 서버 통신 재구현 (#29)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Network/DataModel/Auth/ResignRequest.swift
  WAL/WAL/Network/Service/Auth/AuthService.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
Labels: 코드리뷰좀제발, 서버통신, 훌이킴

#38 [Fix] 히스토리 액션시트 구현 (#33)
  WAL/WAL/Network/Service/Create/CreateService.swift
  WAL/WAL/Network/Service/History/HistoryService.swift
  WAL/WAL/Network/Service/Main/MainService.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
  WAL/WAL/Screen/History/View/HistoryTableViewCell.swift
Labels: 코드리뷰좀제발, 로직구현, 이준

#41 [Fix] Main 오류 수정
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Resource/Support/Info.plist
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/Model/MainDataModel.swift
  WAL/WAL/Screen/Main/View/MainContentView.swift
  WAL/WAL/Screen/Main/View/MainItemCell.swift
Labels: 오류해결, 코드리뷰좀제발, 소깡이

#45 [Feat] 공유하기 구현 (#42)
  WAL/WAL/Global/Extension/UIView+.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
Labels: 오류해결, 로직구현, 소깡이

#44 [Fix] 히스토리 뷰 셀 재사용 문제 (#39)
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
Labels: 오류해결, 코드리뷰좀제발, 이준

#36 [Fix] Auth 오류 및 상황 별 분기처리 대응 (#27)
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Global/Constant.swift
  WAL/WAL/Global/Extension/NSNotification.Name+.swift
  WAL/WAL/Network/API/Onboard/OnboardAPI.swift
  WAL/WAL/Network/API/Setting/SettingAPI.swift
  WAL/WAL/Network/Service/Auth/AuthService.swift
  WAL/WAL/Network/Utility/BaseTargetType.swift
  WAL/WAL/Network/Utility/MoyaLoggerPlugin.swift
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Resource/Support/Info.plist
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Onboarding/View/AlarmCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/CategoryCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/OnboardingCollectionViewCell.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/View/Component/AlarmView.swift
  WAL/WAL/Screen/Setting/View/Component/ZanzanView.swift
  WAL/WAL/Screen/Setting/View/MyInfoTableViewCell.swift
  WAL/WAL/Screen/Setting/View/ResignTableViewCell.swift
  WAL/WAL/Screen/Setting/View/SettingAlarmCollectionViewCell.swift
  WAL/WAL/Screen/Setting/View/SettingTableViewCell.swift
Labels: 코드리뷰좀제발, 훌이킴
