Repository zanzanbari/WAL, pull requests merged in 2022-11, with the labels that each got.

#68 [Fix] 히스토리 뷰 3차 QA (#61)
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
  WAL/WAL/Screen/History/View/HistoryCompleteHeaderView.swift
  WAL/WAL/Screen/History/View/HistoryTableViewCell.swift
Labels: 오류해결, 이준

#70 [Fix] 3차 QA 반영
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/BaseTableViewCell.swift
  WAL/WAL/Global/BaseViewController.swift
  WAL/WAL/Global/Component/LoadingView.swift
  WAL/WAL/Global/Extension/UIViewController+.swift
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Onboarding/View/CategoryCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/OnboardingCollectionViewCell.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/View/Component/AlarmView.swift
  WAL/WAL/Screen/Setting/View/Component/MenuButton.swift
  WAL/WAL/Screen/Setting/View/MyInfoTableViewCell.swift
  WAL/WAL/Screen/Setting/View/ResignTableViewCell.swift
  WAL/WAL/Screen/Setting/View/SettingTableViewCell.swift
Labels: 코드리뷰좀제발, 훌이킴

#74 [Fix] 탈퇴 후 24시간 이내 재가입 불가 알림 문제 해결
  WAL/Podfile.lock
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
Labels: 오류해결, 훌이킴

#73 [Fix] 만들기 화면 3차 QA
  WAL/WAL/Screen/Create/Controller/CreateInformationViewController.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
Labels: 오류해결, 밴톨이

#75 [Fix] Main Response Data 수정 (#71)
  WAL/WAL/Network/API/Main/MainAPI.swift
  WAL/WAL/Network/DataModel/Main/MainResponse.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/View/MainItemCell.swift
Labels: 서버통신, 소깡이
