Repository zanzanbari/WAL, pull requests merged in 2022-12, with the labels that each got.

#77 [Fix] Main 왈뿡이 상태 분기처리 및 코드 개선 (#76)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/Model/MainDataModel.swift
  WAL/WAL/Screen/Main/Model/WALContentType.swift
  WAL/WAL/Screen/Main/Model/WALDataType.swift
Labels: 오류해결, 코드리뷰좀제발, 소깡이

#78 [Fix] 토큰 이슈 MoyaLoggerPlugin 코드 정리해서 로그아웃 되도록 우선처리
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/Component/LoadingView.swift
  WAL/WAL/Global/Constant.swift
  WAL/WAL/Global/SocialType.swift
  WAL/WAL/Global/UserDefaulstHelper.swift
  WAL/WAL/Network/API/Setting/SettingAPI.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Network/Utility/MoyaLoggerPlugin.swift
  WAL/WAL/Network/Utility/TokenManager.swift
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Onboarding/View/AlarmCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/BaseCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/CategoryCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/Component/CardButton.swift
  WAL/WAL/Screen/Onboarding/View/Component/TimeButton.swift
  WAL/WAL/Screen/Onboarding/View/OnboardingCollectionViewCell.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/Controller/ZanzanbariViewController.swift
  WAL/WAL/Screen/Setting/View/MyInfoTableViewCell.swift
  WAL/WAL/Screen/Setting/View/SettingAlarmCollectionViewCell.swift
  WAL/WAL/Screen/Setting/View/SettingTableViewCell.swift
  WAL/WAL/Screen/Splash/SplahViewController.swift
Labels: 코드리뷰좀제발, P0

#79 [Fix] Main 코드 개선 및 QA 수정 (#76)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/Extension/NSNotification.Name+.swift
  WAL/WAL/Network/API/Main/MainAPI.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/View/MainContentView.swift
  WAL/WAL/Screen/Main/View/MainTitleView.swift
Labels: 오류해결, 코드리뷰좀제발, P0, 소깡이

#82 [FEAT] #81 - fastlane match 설정
  WAL/Gemfile
  WAL/Gemfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/fastlane/Appfile
  WAL/fastlane/Fastfile
  WAL/fastlane/Matchfile
  WAL/fastlane/metadata/copyright.txt
  WAL/fastlane/metadata/ko/apple_tv_privacy_policy.txt
  WAL/fastlane/metadata/ko/description.txt
  WAL/fastlane/metadata/ko/keywords.txt
  WAL/fastlane/metadata/ko/marketing_url.txt
  WAL/fastlane/metadata/ko/name.txt
  WAL/fastlane/metadata/ko/privacy_url.txt
  WAL/fastlane/metadata/ko/promotional_text.txt
  WAL/fastlane/metadata/ko/release_notes.txt
  WAL/fastlane/metadata/ko/subtitle.txt
  WAL/fastlane/metadata/ko/support_url.txt
  WAL/fastlane/metadata/primary_category.txt
  WAL/fastlane/metadata/primary_first_sub_category.txt
  WAL/fastlane/metadata/primary_second_sub_category.txt
  WAL/fastlane/metadata/review_information/demo_password.txt
  WAL/fastlane/metadata/review_information/demo_user.txt
  WAL/fastlane/metadata/review_information/email_address.txt
  WAL/fastlane/metadata/review_information/first_name.txt
  WAL/fastlane/metadata/review_information/last_name.txt
  WAL/fastlane/metadata/review_information/notes.txt
  WAL/fastlane/metadata/review_information/phone_number.txt
  WAL/fastlane/metadata/secondary_category.txt
  WAL/fastlane/metadata/secondary_first_sub_category.txt
  WAL/fastlane/metadata/secondary_second_sub_category.txt
Labels: 이준
