Repository zanzanbari/WAL, pull requests merged in 2022-09, with the labels that each got.

#49 [Fix] 환경설정, 온보딩 QA 반영
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Global/Extension/Transition+.swift
  WAL/WAL/Resource/Support/Info.plist
  WAL/WAL/Screen/Create/View/WALPopupView.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Onboarding/View/AlarmCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/CategoryCollectionViewCell.swift
  WAL/WAL/Screen/Onboarding/View/Component/CardButton.swift
  WAL/WAL/Screen/Onboarding/View/OnboardingCollectionViewCell.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/Controller/ZanzanbariViewController.swift
  WAL/WAL/Screen/Setting/View/Component/ResignHeaderView.swift
Labels: 코드리뷰좀제발, 훌이킴

#52 [Fix] 메인 QA (#46)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/View/MainContentView.swift
Labels: 오류해결, 코드리뷰좀제발, 소깡이

#53 [Fix] 히스토리 뷰 1차 QA (#48)
  WAL/WAL/Global/Protocol/Protocol.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
  WAL/WAL/Screen/History/View/HistoryCompleteHeaderView.swift
  WAL/WAL/Screen/History/View/HistoryReserveHeaderView.swift
  WAL/WAL/Screen/History/View/HistoryTableViewCell.swift
Labels: 오류해결, 코드리뷰좀제발, 이준

#54 [Feat] LoginView Animation / Gif 반영
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Network/Service/Auth/AuthService.swift
  WAL/WAL/Network/Service/Create/CreateService.swift
  WAL/WAL/Network/Service/History/HistoryService.swift
  WAL/WAL/Network/Service/Main/MainService.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Network/Utility/MoyaLoggerPlugin.swift
  WAL/WAL/Resource/Storyboard/Launch Screen.storyboard
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Resource/loginGif.gif
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
Labels: 오류해결, 코드리뷰좀제발, 훌이킴

#55 [Fix] .gif 파일 추가 및 파일 위치 이슈 해결
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Resource/Lottie/login.json
  WAL/WAL/Resource/Lottie/login500.gif
  WAL/WAL/Resource/Lottie/mintPaw.json
  WAL/WAL/Resource/Lottie/orangePaw.json
Labels: 오류해결, 소깡이

#58 [Fix] Main QA (#46)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/Model/WALStatus.swift
Labels: 코드리뷰좀제발, 소깡이

#59 [Fix] Creating QA (#50)
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Screen/Create/Controller/CreateInformationViewController.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
Labels: 오류해결, 코드리뷰좀제발, 밴톨이

#63 [Fix] 2차 QA 반영
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Global/Component/LoadingView.swift
  WAL/WAL/Global/Constant.swift
  WAL/WAL/Global/UserDefaulstHelper.swift
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Network/Service/Auth/AuthService.swift
  WAL/WAL/Network/Service/Create/CreateService.swift
  WAL/WAL/Network/Service/History/HistoryService.swift
  WAL/WAL/Network/Service/Main/MainService.swift
  WAL/WAL/Network/Utility/BaseTargetType.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Network/Utility/MoyaLoggerPlugin.swift
  WAL/WAL/Resource/Lottie/loading.json
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/MypageViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/View/MyInfoTableViewCell.swift
  WAL/WAL/Screen/Setting/View/ResignTableViewCell.swift
Labels: 코드리뷰좀제발, 훌이킴

#60 [Fix] 히스토리 뷰 2차 QA (#57)
  WAL/WAL/Global/Extension/String+.swift
  WAL/WAL/Global/Protocol/Protocol.swift
  WAL/WAL/Network/DataModel/History/HistoryResponse.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
  WAL/WAL/Screen/History/View/HistoryTableViewCell.swift
Labels: 오류해결, 코드리뷰좀제발, 이준

#64 [Fix] FcmToken 강제언래핑으로 인해 nil 문제 해결
  WAL/Podfile
  WAL/Podfile.lock
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Global/Extension/NSNotification.Name+.swift
  WAL/WAL/Global/UserDefaulstHelper.swift
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Network/Service/Auth/AuthService.swift
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
Labels: 코드리뷰좀제발, 훌이킴

#65 [Fix] 로그아웃 대응 및 SceneDelegate 코드 수정 (#35)
  WAL/WAL/Global/UserDefaulstHelper.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
Labels: 오류해결, 코드리뷰좀제발, 훌이킴
