Repository zanzanbari/WAL, pull requests merged in 2023-01, with the labels that each got.

#85 [Fix] 앱언어 설정, 스플래시 수정, 재발급 이슈 해결
  WAL/WAL/Network/API/Main/MainAPI.swift
  WAL/WAL/Network/DataModel/Auth/Reissue.swift
  WAL/WAL/Network/Utility/MoyaLoggerPlugin.swift
  WAL/WAL/Network/Utility/TokenManager.swift
  WAL/WAL/Resource/Asset/Asset.xcassets/wal.imageset/Contents.json
  WAL/WAL/Resource/Asset/Asset.xcassets/wal.imageset/icn_wal.png
  WAL/WAL/Resource/Asset/Asset.xcassets/wal.imageset/icn_wal@2x.png
  WAL/WAL/Resource/Asset/Asset.xcassets/wal.imageset/icn_wal@3x.png
  WAL/WAL/Resource/Storyboard/Launch Screen.storyboard
  WAL/WAL/Resource/Support/Info.plist
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Setting/Controller/SubController/LogoutPopupViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
Labels: 코드리뷰좀제발, 훌이킴

#88 [Fix] Main 코드 개선 및 코드 최신화 (#80)
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
Labels: 코드리뷰좀제발, 소깡이

#90 [Fix] nickname으로 사용자가 서비스에 가입되었는지 분기처리
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
Labels: 오류해결, 코드리뷰좀제발, 훌이킴

#91 [Fix] 만들기 화면 3차 QA 반영 (#67)
  WAL/WAL/Screen/Create/Controller/CreateInformationViewController.swift
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
  WAL/WAL/Screen/Create/View/ReservationTableViewCell.swift
Labels: 오류해결, 코드리뷰좀제발, 밴톨이

#93 [Fix] nickname 빈문자열로 넘어오는 부분 분기처리 오류 해결
  WAL/WAL/Global/Component/LoadingView.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
Labels: 코드리뷰좀제발
