Repository zanzanbari/WAL, pull requests merged in 2023-05, with the labels that each got.

#98 [Feat] API(v2) 연결 및 메인화면 MVVM 구조로 개선 (#96)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Global/Extension/ObservableType+.swift
  WAL/WAL/Global/Extension/UICollectionViewCell+.swift
  WAL/WAL/Network/API/Main/MainAPI.swift
  WAL/WAL/Network/DataModel/Main/AlarmTimeType.swift
  WAL/WAL/Network/DataModel/Main/MainResponse.swift
  WAL/WAL/Network/DataModel/Main/TodayWalList.swift
  WAL/WAL/Network/DataModel/Main/WalCategoryType.swift
  WAL/WAL/Network/Service/Main/MainService.swift
  WAL/WAL/Network/Utility/BaseTargetType.swift
  WAL/WAL/Network/Utility/GeneralAPI.swift
  WAL/WAL/Network/Utility/NetworkResult.swift
  WAL/WAL/Network/Utility/Protocol/BaseResponse.swift
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/Model/WALContentType.swift
  WAL/WAL/Screen/Main/View/MainContentView.swift
  WAL/WAL/Screen/Main/View/MainItemCell.swift
  WAL/WAL/Screen/Main/ViewModel/MainViewModel.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Splash/SplahViewController.swift
Labels: 코드리뷰좀제발, 서버통신, 로직구현, 소깡이, 리팩토링

#105 [Feat] 메인화면 서브타이틀 API 연결 및 로직 구현 (#100)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Network/API/Main/MainAPI.swift
  WAL/WAL/Network/DataModel/Main/MainSubtitle.swift
  WAL/WAL/Network/Service/Main/MainService.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/Model/MainSubtitleStatus.swift
  WAL/WAL/Screen/Main/Model/WalDataType.swift
  WAL/WAL/Screen/Main/Model/WalStatus.swift
  WAL/WAL/Screen/Main/View/MainItemCell.swift
  WAL/WAL/Screen/Main/ViewModel/MainViewModel.swift
Labels: P0, 서버통신, 로직구현, 소깡이

#109 [Feat] Interceptor 재시도 횟수 제한 및 코드 수정
  WAL/WAL/Global/Extension/UIViewController+.swift
  WAL/WAL/Network/API/Auth/AuthAPI.swift
  WAL/WAL/Network/API/Onboard/OnboardAPI.swift
  WAL/WAL/Network/Utility/Interceptor.swift
  WAL/WAL/Network/Utility/MoyaLoggerPlugin.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
Labels: 오류해결, 코드리뷰좀제발, P0, 서버통신, 로직구현, 훌이킴

#110 [Feat] 히스토리 서버 연결 (#103)
  WAL/Podfile.lock
  WAL/WAL.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WAL/WAL/Network/API/History/HistoryAPI.swift
  WAL/WAL/Network/DataModel/History/HistoryResponse.swift
  WAL/WAL/Network/Service/History/HistoryService.swift
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
  WAL/WAL/Screen/History/View/HistoryTableViewCell.swift
Labels: 서버통신, 이준

#112 [Add] GoogleService-Info.plist 수정 (#108)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/GoogleService-Info.plist
Labels: 코드리뷰좀제발, 소깡이
