Repository zanzanbari/WAL, pull requests merged in 2023-08, with the labels that each got.

#128 [Fix] 메인서브타이틀 ""로 표출되는 이슈 수정 (#127)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/View/MainTitleView.swift
  WAL/WAL/Screen/Main/ViewModel/MainViewModel.swift
Labels: 오류해결, 소깡이

#131 [Fix] 히스토리에 토큰 재발급 로직 추가 (#130)
  WAL/WAL/Screen/History/Controller/HistoryViewController.swift
Labels: 서버통신, 이준

#132 [Fix] 토큰 재발급 로직 추가 (#129)
  WAL/WAL.xcodeproj/project.pbxproj
  WAL/WAL/Screen/Create/Controller/CreateViewController.swift
Labels: 서버통신, 밴톨이

#133 [Fix] 설정에 재발급 로직 추가 (#122)
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingCategoryViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/EditNicknameViewController.swift
  WAL/WAL/Screen/Setting/Controller/SubController/ResignViewController.swift
  WAL/WAL/Screen/Setting/Model/Setting.swift
Labels: 오류해결, 코드리뷰좀제발, 훌이킴

#136 [Hotfix] MainViewModel init 시점 및 메인상태 UI 업데이트 로직 수정 (#134)
  WAL/WAL/Resource/Support/AppDelegate.swift
  WAL/WAL/Resource/Support/SceneDelegate.swift
  WAL/WAL/Screen/Login/Controller/LoginViewController.swift
  WAL/WAL/Screen/Main/Controller/MainViewController.swift
  WAL/WAL/Screen/Main/ViewModel/MainViewModel.swift
  WAL/WAL/Screen/Onboarding/Controller/OnboardCompleteViewController.swift
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
Labels: 오류해결, 코드리뷰좀제발, P0, 소깡이

#139 [Fix] 푸쉬알림 동의 상태에 따른 토글 on/off 반영 (#138)
  WAL/WAL/Screen/Setting/Controller/SettingAlarmViewController.swift
Labels: 코드리뷰좀제발, 훌이킴
